/**
 * @file agentService.js
 * @module services
 *
 * Agent service for GENERATIVE AI FOR EVERYONE.
 *
 * REAL MODE (VITE_USE_MOCK=false):
 *   Uses SSE streaming: GET /api/agent/run-stream/:projectId
 *   Uses fetch() with Bearer token (EventSource doesn't support custom headers).
 *   onEvent(type, data) is called for each SSE event.
 *
 * MOCK MODE (VITE_USE_MOCK=true):
 *   Uses local goal-aware mock workflow for offline development/testing.
 */

import { API_URL, USE_MOCK, getStoredToken, apiFetch } from '@/config/api';
import { TaskStatus, WorkflowStatus, TaskType } from '@/constants/workflow';
import { MOCK_PROJECTS } from './mockData';

// --- MOCK: goal classification helpers ---

function classifyGoal(goal) {
  const g = (goal || '').toLowerCase();
  if (/website|landing|page|html|web|frontend/.test(g)) return 'website';
  if (/code|function|algorithm|api|script|program/.test(g)) return 'code';
  if (/essay|article|blog|report|write|content/.test(g)) return 'text';
  if (/analyze|analyse|data|insight|review/.test(g)) return 'analysis';
  return 'general';
}

function extractSubject(goal) {
  const g = goal || '';
  const m = g.match(/(?:for\s+(?:a\s+|an\s+)?|about\s+|called\s+|named\s+)([\w\s]{2,30})/i);
  if (m) return m[1].trim();
  const words = g.trim().split(/\s+/);
  return words.slice(-Math.min(3, words.length)).join(' ');
}

function buildGoalAwareWorkflow(goal) {
  const type    = classifyGoal(goal);
  const subject = extractSubject(goal);
  const wfId    = `wf-${Date.now()}`;

  const taskSets = {
    website: [
      { id: 'task-1', type: TaskType.TEXT_GENERATION,    title: `Plan ${subject} website`, description: 'Define site structure and sections', dependencies: [] },
      { id: 'task-2', type: TaskType.CODE_GENERATION,    title: 'Generate HTML/CSS',         description: `Full website HTML for ${subject}`, dependencies: ['task-1'] },
      { id: 'task-3', type: TaskType.WEBSITE_GENERATION, title: 'Assemble final site',        description: 'Combine content into deployable page', dependencies: ['task-2'] },
      { id: 'task-4', type: TaskType.VALIDATION,         title: 'Validate output',            description: 'Check HTML structure and completeness', dependencies: ['task-3'] },
    ],
    code: [
      { id: 'task-1', type: TaskType.TEXT_GENERATION,    title: `Plan ${subject} solution`, description: 'Define approach and algorithm', dependencies: [] },
      { id: 'task-2', type: TaskType.CODE_GENERATION,    title: `Generate ${subject} code`, description: `Implement the ${subject} in code`, dependencies: ['task-1'] },
      { id: 'task-3', type: TaskType.VALIDATION,         title: 'Validate code',            description: 'Check syntax and logic correctness', dependencies: ['task-2'] },
    ],
    text: [
      { id: 'task-1', type: TaskType.TEXT_GENERATION, title: `Research ${subject}`,  description: 'Gather key points and facts', dependencies: [] },
      { id: 'task-2', type: TaskType.TEXT_GENERATION, title: `Draft ${subject}`,    description: 'Write the main content', dependencies: ['task-1'] },
      { id: 'task-3', type: TaskType.VALIDATION,      title: 'Review and validate', description: 'Check quality and completeness', dependencies: ['task-2'] },
    ],
    analysis: [
      { id: 'task-1', type: TaskType.TEXT_GENERATION, title: `Analyse ${subject}`,   description: 'Break down the topic', dependencies: [] },
      { id: 'task-2', type: TaskType.TEXT_GENERATION, title: 'Generate insights',    description: 'Draw key conclusions', dependencies: ['task-1'] },
      { id: 'task-3', type: TaskType.VALIDATION,      title: 'Validate analysis',    description: 'Verify reasoning quality', dependencies: ['task-2'] },
    ],
    general: [
      { id: 'task-1', type: TaskType.TEXT_GENERATION, title: `Plan: ${subject}`,    description: 'Outline approach', dependencies: [] },
      { id: 'task-2', type: TaskType.TEXT_GENERATION, title: 'Generate content',    description: 'Produce the main output', dependencies: ['task-1'] },
      { id: 'task-3', type: TaskType.VALIDATION,      title: 'Validate output',     description: 'Quality check', dependencies: ['task-2'] },
    ],
  };

  const rawTasks = taskSets[type];
  const tasks = rawTasks.map(t => ({ ...t, status: TaskStatus.PENDING, output: null }));
  return { id: wfId, goal, status: WorkflowStatus.PENDING, tasks };
}

function generateMockOutputs(goal, tasks) {
  const subject = extractSubject(goal);
  const type    = classifyGoal(goal);
  const outputs = {};

  tasks.forEach(task => {
    if (task.type === TaskType.CODE_GENERATION) {
      const cls = subject.replace(/\s+/g, '');
      outputs[task.id] = {
        content: `// ${subject} -- generated by Generative AI for Everyone\nclass ${cls} {\n  constructor() {\n    this.name = '${subject}';\n  }\n  execute() {\n    return { success: true, result: 'Generated for: ${goal}' };\n  }\n}\n\nmodule.exports = new ${cls}();`,
        language: 'javascript',
        model: 'mock-gpt',
      };
    } else if (task.type === TaskType.WEBSITE_GENERATION || (type === 'website' && task.id === 'task-3')) {
      outputs[task.id] = {
        content: `<!DOCTYPE html><html><head><title>${subject}</title><style>body{font-family:sans-serif;max-width:900px;margin:auto;padding:2rem;background:#0a0a0a;color:#F2F0E4}h1{color:#D4AF37;border-bottom:1px solid #D4AF37;padding-bottom:.5rem}</style></head><body><h1>${subject}</h1><p>AI-generated content for: ${goal}</p><section><h2>Overview</h2><p>This page was generated by the Generative AI for Everyone platform based on your goal.</p></section></body></html>`,
        model: 'mock-html',
      };
    } else {
      outputs[task.id] = {
        content: `## ${task.title}\n\nGenerated content for **${subject}** based on your goal:\n\n> ${goal}\n\nThis AI output was produced by the ${task.type} module. The content is contextually aware of your specific request and has been validated for quality and completeness.`,
        model: 'mock-llm',
      };
    }
  });
  return outputs;
}

// --- MOCK STATE ---
let _mockWorkflow = null;
let _mockTaskIndex = 0;
let _mockOutputs = {};

// --- REAL MODE: SSE Stream ---

/**
 * Start a workflow run via SSE streaming.
 * Calls onEvent(type, data) for each SSE event received.
 * Returns a promise that resolves with the final workflow_complete data.
 */
export async function startWorkflowStream(projectId, onEvent) {
  const token = getStoredToken();
  const url   = `${API_URL}/api/agent/run-stream/${projectId}`;

  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Accept': 'text/event-stream',
      ...(token ? { 'Authorization': `Bearer ${token}` } : {}),
    },
  });

  if (!response.ok) {
    const body = await response.json().catch(() => ({}));
    const err = new Error(body?.message || `Agent stream error ${response.status}`);
    err.status = response.status;
    throw err;
  }

  const reader  = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  let currentEvent = null;
  let finalResult = null;

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\n');
    buffer = lines.pop();

    for (const line of lines) {
      if (line.startsWith('event:')) {
        currentEvent = line.slice(6).trim();
      } else if (line.startsWith('data:')) {
        const rawData = line.slice(5).trim();
        try {
          const data = JSON.parse(rawData);
          if (currentEvent && currentEvent !== 'ping') {
            onEvent(currentEvent, data);
            if (currentEvent === 'workflow_complete') finalResult = data;
          }
        } catch (_) { /* ignore malformed JSON */ }
        currentEvent = null;
      }
      // SSE comment / keep-alive lines starting with ':' are ignored
    }
  }

  return finalResult;
}

// --- UNIFIED AGENT SERVICE ---

const agentService = {
  async startWorkflow(goal, projectId) {
    if (USE_MOCK) {
      _mockWorkflow  = buildGoalAwareWorkflow(goal);
      _mockTaskIndex = 0;
      _mockOutputs   = generateMockOutputs(goal, _mockWorkflow.tasks);
      _mockWorkflow.status = WorkflowStatus.RUNNING;
      _mockWorkflow.tasks[0].status = TaskStatus.RUNNING;
      return { workflowId: _mockWorkflow.id, workflow: { ..._mockWorkflow } };
    }
    throw new Error('In real mode, use startWorkflowStream() directly.');
  },

  advanceMock() {
    if (!_mockWorkflow) return;
    const tasks = _mockWorkflow.tasks;
    if (_mockTaskIndex < tasks.length) {
      const current = tasks[_mockTaskIndex];
      current.status = TaskStatus.COMPLETED;
      current.output = _mockOutputs[current.id] || { content: 'Generated output' };
      _mockTaskIndex++;
      if (_mockTaskIndex < tasks.length) {
        tasks[_mockTaskIndex].status = TaskStatus.RUNNING;
      } else {
        _mockWorkflow.status = WorkflowStatus.COMPLETED;
      }
    }
  },

  async getWorkflow(workflowId) {
    return _mockWorkflow ? { ..._mockWorkflow } : null;
  },

  async cancelWorkflow(workflowId) {
    if (_mockWorkflow) _mockWorkflow.status = WorkflowStatus.FAILED;
  },

  async getHistory(projectId) {
    if (USE_MOCK) {
      return (MOCK_PROJECTS || []).map(p => ({
        _id: `hist-${p.id}`, action: 'generation_completed',
        prompt: p.prompt, status: 'success',
        metadata: { workflowId: `wf-${p.id}`, taskCount: 4 },
        createdAt: new Date().toISOString(),
      }));
    }
    const data = await apiFetch(`/api/agent/history/${projectId}`);

    return data.data || [];
  },
};

export default agentService;
