import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import DecoFrame from '../ui/DecoFrame';
import { FileText, Code, Globe, ShieldCheck, Layers } from 'lucide-react';
import { TaskType } from '@/constants/workflow';

// ─── Tab config ───────────────────────────────────────────────────────────────

const TABS = [
  { id: 'OVERVIEW',  label: 'OVERVIEW',  icon: Layers     },
  { id: 'TEXT',      label: 'TEXT',      icon: FileText   },
  { id: 'CODE',      label: 'CODE',      icon: Code       },
  { id: 'WEBSITE',   label: 'WEBSITE',   icon: Globe      },
  { id: 'VALIDATE',  label: 'VALIDATION',icon: ShieldCheck },
];

// ─── Overview Tab ─────────────────────────────────────────────────────────────

function OverviewTab({ tasks, goal }) {
  const completed = tasks.filter((t) => t.output);
  if (completed.length === 0) {
    return (
      <div className="py-12 text-center">
        <p className="font-sans text-xs text-[#888888]">
          Generated outputs will appear here as tasks complete.
        </p>
      </div>
    );
  }
  return (
    <div className="space-y-4">
      {goal && (
        <p className="font-sans text-xs text-[#888888] italic border-l-2 border-[#D4AF37]/30 pl-3 leading-relaxed">
          "{goal}"
        </p>
      )}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {completed.map((task) => (
          <div key={task.id} className="bg-[#0A0A0A] border border-[#D4AF37]/20 p-4">
            <span className="font-sans text-[10px] tracking-widest text-[#D4AF37] block mb-1 uppercase">
              {task.type?.replace('_', ' ')}
            </span>
            <p className="font-display text-sm uppercase tracking-wider text-[#F2F0E4]">
              {task.title}
            </p>
            <span className="font-sans text-[10px] text-[#4CAF50] mt-1.5 block">✓ READY</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── Text Tab ─────────────────────────────────────────────────────────────────

function TextTab({ tasks }) {
  const textTask = tasks.find((t) =>
    (t.type === TaskType.TEXT_GENERATION) && t.output?.content
  );
  if (!textTask) return (
    <div className="py-12 text-center">
      <p className="font-sans text-xs text-[#888888]">Text generation output will appear here.</p>
    </div>
  );
  return (
    <div className="bg-[#0A0A0A] border border-[#D4AF37]/20 p-6 space-y-4 max-h-96 overflow-y-auto">
      <div className="flex items-center justify-between pb-3 border-b border-[#D4AF37]/10">
        <span className="font-sans text-[10px] tracking-widest text-[#D4AF37] uppercase">{textTask.title}</span>
        {textTask.output.wordCount && (
          <span className="font-sans text-[10px] text-[#888888]">{textTask.output.wordCount} words</span>
        )}
      </div>
      <p className="font-sans text-xs text-[#F2F0E4]/85 leading-relaxed whitespace-pre-wrap">
        {textTask.output.content}
      </p>
      {textTask.output.model && (
        <p className="font-sans text-[10px] text-[#888888]/50 border-t border-[#D4AF37]/8 pt-3">
          Generated by: {textTask.output.model}
        </p>
      )}
    </div>
  );
}

// ─── Code Tab ────────────────────────────────────────────────────────────────

function CodeTab({ tasks }) {
  const codeTask = tasks.find((t) =>
    (t.type === TaskType.CODE_GENERATION) && t.output?.code
  );
  if (!codeTask) return (
    <div className="py-12 text-center">
      <p className="font-sans text-xs text-[#888888]">Code generation output will appear here.</p>
    </div>
  );
  return (
    <div className="bg-[#0A0A0A] border border-[#D4AF37]/20 p-0 overflow-hidden">
      <div className="flex items-center justify-between px-5 py-3 border-b border-[#D4AF37]/15 bg-[#141414]">
        <span className="font-mono text-[11px] text-[#D4AF37]">{codeTask.title.toLowerCase().replace(/ /g, '_')}.{codeTask.output.language === 'javascript' ? 'js' : codeTask.output.language || 'txt'}</span>
        <div className="flex items-center gap-3">
          <span className="font-sans text-[10px] text-[#888888] uppercase tracking-wider">{codeTask.output.language}</span>
          {codeTask.output.valid !== undefined && (
            <span className={`font-sans text-[10px] tracking-widest uppercase ${codeTask.output.valid ? 'text-[#4CAF50]' : 'text-[#EF5350]'}`}>
              {codeTask.output.valid ? '✓ VALID' : '✕ INVALID'}
            </span>
          )}
        </div>
      </div>
      <pre className="font-mono text-[11px] text-[#D4AF37]/85 leading-relaxed p-5 overflow-x-auto max-h-80">
        <code>{codeTask.output.code}</code>
      </pre>
    </div>
  );
}

// ─── Website Tab ─────────────────────────────────────────────────────────────

function WebsiteTab({ tasks }) {
  const webTask = tasks.find((t) =>
    (t.type === TaskType.WEBSITE_GENERATION) && t.output
  );
  if (!webTask) return (
    <div className="py-12 text-center">
      <p className="font-sans text-xs text-[#888888]">Website generation output will appear here.</p>
    </div>
  );
  return (
    <DecoFrame>
      {/* Mock browser bar */}
      <div className="flex items-center justify-between pb-3 mb-4 border-b border-[#D4AF37]/15">
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 bg-[#D4AF37]" />
          <div className="w-2 h-2 bg-[#D4AF37]/50" />
          <div className="w-2 h-2 bg-[#D4AF37]/20" />
        </div>
        <div className="font-sans text-[11px] tracking-wider text-[#D4AF37] bg-[#141414] px-4 py-1 border border-[#D4AF37]/25">
          ai-generated-website.local
        </div>
        <span className="font-sans text-[9px] tracking-widest text-[#888888]">PREVIEW</span>
      </div>

      {/* Files list */}
      {webTask.output.files?.length > 0 && (
        <div className="flex flex-wrap gap-2 mb-4">
          {webTask.output.files.map((f) => (
            <span key={f} className="font-mono text-[10px] bg-[#0A0A0A] border border-[#D4AF37]/20 px-2 py-0.5 text-[#D4AF37]">
              {f}
            </span>
          ))}
        </div>
      )}

      {/* Interactive Website Preview */}
      <div className="bg-[#050505] border border-[#D4AF37]/15 p-2 min-h-[360px]">
        <iframe
          srcDoc={typeof webTask.output.content === 'string' ? webTask.output.content : ''}
          title="Generated Website Preview"
          className="w-full h-[420px] bg-white border border-[#222222]"
          sandbox="allow-scripts allow-modals"
        />
      </div>

      {webTask.output.pageCount && (
        <p className="font-sans text-[10px] text-[#888888] mt-3 flex items-center justify-between">
          <span>{webTask.output.pageCount} page generated · <span className="text-[#4CAF50]">✓ Build passed</span></span>
          {webTask.output.model && <span className="font-mono text-[9px] text-[#888888]/60">{webTask.output.model}</span>}
        </p>
      )}
    </DecoFrame>
  );
}

// ─── Validation Tab ───────────────────────────────────────────────────────────

function ValidateTab({ tasks }) {
  const valTask = tasks.find((t) =>
    (t.type === TaskType.VALIDATION) && t.output
  );
  if (!valTask) return (
    <div className="py-12 text-center">
      <p className="font-sans text-xs text-[#888888]">Validation report will appear here.</p>
    </div>
  );
  const { checks, valid, score } = valTask.output;
  return (
    <div className="space-y-4">
      <div className={`flex items-center gap-3 p-4 border ${valid ? 'border-[#4CAF50]/30 bg-[#4CAF50]/5' : 'border-[#EF5350]/30 bg-[#EF5350]/5'}`}>
        <span className={`font-sans text-sm font-bold ${valid ? 'text-[#4CAF50]' : 'text-[#EF5350]'}`}>
          {valid ? '✓ ALL CHECKS PASSED' : '✕ VALIDATION FAILED'}
        </span>
        {score !== undefined && (
          <span className="font-sans text-[11px] text-[#888888] ml-auto">
            Score: <strong className="text-[#D4AF37]">{(score * 100).toFixed(0)}%</strong>
          </span>
        )}
      </div>
      {checks?.map((c) => (
        <div key={c.name} className="flex items-center justify-between py-2.5 border-b border-[#D4AF37]/8 last:border-0">
          <span className="font-mono text-xs text-[#F2F0E4]/70">{c.name}</span>
          <span className={`font-sans text-[10px] tracking-widest uppercase ${c.status === 'PASS' ? 'text-[#4CAF50]' : 'text-[#EF5350]'}`}>
            {c.status === 'PASS' ? '✓ PASS' : '✕ FAIL'}
          </span>
        </div>
      ))}
    </div>
  );
}

// ─── MAIN COMPONENT ───────────────────────────────────────────────────────────

/**
 * OutputViewer — Multi-tab output display.
 *
 * Accepts:
 *   tasks        — array of Task objects (from useWorkflow)
 *   projectGoal  — string (shown in overview)
 *
 * Falls back to static static EcoCampus preview if no tasks are provided
 * (for backwards-compatibility with the legacy workspace page).
 */
export default function OutputViewer({ tasks = [], projectGoal }) {
  const [activeTab, setActiveTab] = useState('OVERVIEW');

  return (
    <div className="bg-[#141414] border border-[#D4AF37]/25 p-5 space-y-5">
      {/* Header + Tabs */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-[#D4AF37]/15">
        <span className="font-sans text-[10px] tracking-[0.3em] uppercase text-[#D4AF37]">
          OUTPUT ARTIFACT VIEWER
        </span>
        <div className="flex flex-wrap gap-1.5">
          {TABS.map(({ id, label, icon: Icon }) => (
            <button
              key={id}
              onClick={() => setActiveTab(id)}
              className={`font-sans text-[10px] tracking-[0.15em] uppercase px-3 py-1.5 border transition-all flex items-center gap-1.5 ${
                activeTab === id
                  ? 'bg-[#D4AF37] border-[#D4AF37] text-[#0A0A0A] font-bold shadow-gold'
                  : 'bg-[#0A0A0A] border-[#D4AF37]/25 text-[#888888] hover:border-[#D4AF37] hover:text-[#F2F0E4]'
              }`}
            >
              <Icon size={10} />
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* Tab Content */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeTab}
          initial={{ opacity: 0, y: 6 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -6 }}
          transition={{ duration: 0.18 }}
        >
          {activeTab === 'OVERVIEW'  && <OverviewTab tasks={tasks} goal={projectGoal} />}
          {activeTab === 'TEXT'      && <TextTab tasks={tasks} />}
          {activeTab === 'CODE'      && <CodeTab tasks={tasks} />}
          {activeTab === 'WEBSITE'   && <WebsiteTab tasks={tasks} />}
          {activeTab === 'VALIDATE'  && <ValidateTab tasks={tasks} />}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
